// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(pixel_data,7,0);
        VL_IN8(kernel_data,7,0);
        VL_IN8(input_valid,0,0);
        VL_OUT8(output_valid,0,0);
        CData/*0:0*/ multiply_block__DOT__clk;
        CData/*0:0*/ multiply_block__DOT__rst;
        CData/*7:0*/ multiply_block__DOT__pixel_data;
        CData/*7:0*/ multiply_block__DOT__kernel_data;
        CData/*0:0*/ multiply_block__DOT__input_valid;
        CData/*0:0*/ multiply_block__DOT__output_valid;
        CData/*7:0*/ multiply_block__DOT__s2u_to_mult8;
        CData/*0:0*/ multiply_block__DOT__is_neg_1;
        CData/*0:0*/ multiply_block__DOT__is_neg_2;
        CData/*7:0*/ multiply_block__DOT__s2u_inst__DOT__in;
        CData/*7:0*/ multiply_block__DOT__s2u_inst__DOT__out;
        CData/*0:0*/ multiply_block__DOT__s2u_inst__DOT__is_neg;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__clk;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__rst;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__is_neg_in;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__is_neg_out;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__a;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__in_valid;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__output_valid;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__x1;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__x2;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__x3;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__x4;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__x5;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__stage_one_valid;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r2;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r2_temp;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r4;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r4_temp;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r5;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r5_temp;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r6;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__r6_temp;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__stage_two_valid;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__s4;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__s4_temp;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__stage_three_valid;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__t3;
        CData/*7:0*/ multiply_block__DOT__m8__DOT__t3_temp;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__stage_four_valid;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__stage_five_valid;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_1__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_1__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_1__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_1__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_1__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_1__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_1__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_1__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_1__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_2__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_2__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_2__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_2__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_2__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_3__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_3__DOT__b;
    };
    struct {
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_3__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_3__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_3__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_2__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_2__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_2__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_2__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_4__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_4__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_4__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_4__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_4__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_5__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_5__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_5__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_5__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_5__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_6__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_6__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_6__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_6__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_6__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_7__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_7__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_7__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_7__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_7__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_8__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_8__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_8__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_8__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_8__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_9__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_9__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_9__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_9__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_9__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_3__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_3__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_3__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_3__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_10__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_10__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_10__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_10__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_10__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_11__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_11__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_11__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_11__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_11__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_12__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_12__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_12__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_12__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa_12__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_4__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_4__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_4__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_4__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_5__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_5__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_5__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_5__DOT__cout;
    };
    struct {
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa13__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa13__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa13__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa13__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa13__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa14__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa14__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa14__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa14__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa14__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa15__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa15__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa15__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa15__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa15__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa16__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa16__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa16__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa16__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa16__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_6__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_6__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_6__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_6__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa17__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa17__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa17__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa17__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa17__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa18__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa18__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa18__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa18__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa18__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa19__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa19__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa19__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa19__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa19__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa20__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa20__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa20__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa20__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa20__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa21__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa21__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa21__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa21__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa21__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa22__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa22__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa22__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa22__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa22__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa23__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa23__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa23__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa23__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa23__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa24__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa24__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa24__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa24__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa24__DOT__cout;
    };
    struct {
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa25__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa25__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa25__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa25__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa25__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_7__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_7__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_7__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_7__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_8__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_8__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_8__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_8__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_9__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_9__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_9__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_9__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa26__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa26__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa26__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa26__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa26__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa27__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa27__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa27__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa27__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa27__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa28__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa28__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa28__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa28__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa28__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa29__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa29__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa29__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa29__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa29__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa30__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa30__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa30__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa30__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa30__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa31__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa31__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa31__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa31__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa31__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_10__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_10__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_10__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_10__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_11__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_11__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_11__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_11__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_12__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_12__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_12__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_12__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_13__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_13__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_13__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_13__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_14__DOT__a;
    };
    struct {
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_14__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_14__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_14__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa32__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa32__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa32__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa32__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa32__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa33__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa33__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa33__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa33__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa33__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa34__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa34__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa34__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa34__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa34__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa35__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa35__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa35__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa35__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa35__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa36__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa36__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa36__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa36__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa36__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa37__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa37__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa37__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa37__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa37__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa38__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa38__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa38__DOT__cin;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa38__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__fa38__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_15__DOT__a;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_15__DOT__b;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_15__DOT__s;
        CData/*0:0*/ multiply_block__DOT__m8__DOT__ha_15__DOT__cout;
        CData/*0:0*/ multiply_block__DOT__u2s_inst__DOT__is_neg;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__multiply_block__DOT__m8__DOT__clk__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_OUT16(multiply_out,15,0);
        SData/*15:0*/ multiply_block__DOT__multiply_out;
        SData/*15:0*/ multiply_block__DOT__mo;
        SData/*15:0*/ multiply_block__DOT__m8__DOT__out;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__r1;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__r1_temp;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__r3;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__r3_temp;
        SData/*10:0*/ multiply_block__DOT__m8__DOT__s1;
        SData/*10:0*/ multiply_block__DOT__m8__DOT__s1_temp;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__s2;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__s2_temp;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__s3;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__s3_temp;
    };
    struct {
        SData/*13:0*/ multiply_block__DOT__m8__DOT__t1;
        SData/*13:0*/ multiply_block__DOT__m8__DOT__t1_temp;
        SData/*10:0*/ multiply_block__DOT__m8__DOT__t2;
        SData/*10:0*/ multiply_block__DOT__m8__DOT__t2_temp;
        SData/*15:0*/ multiply_block__DOT__m8__DOT__u1;
        SData/*15:0*/ multiply_block__DOT__m8__DOT__u1_temp;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__u2;
        SData/*9:0*/ multiply_block__DOT__m8__DOT__u2_temp;
        SData/*15:0*/ multiply_block__DOT__m8__DOT__sum_temp;
        SData/*15:0*/ multiply_block__DOT__u2s_inst__DOT__in;
        SData/*15:0*/ multiply_block__DOT__u2s_inst__DOT__out;
        IData/*31:0*/ multiply_block__DOT__m8__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ multiply_block__DOT__m8__DOT__unnamedblk1__DOT__unnamedblk2__DOT__j;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 8>, 8> multiply_block__DOT__m8__DOT__partial_products;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<VlUnpacked<CData/*0:0*/, 8>, 8>, false, CData/*0:0*/, 2> __VdlyCommitQueuemultiply_block__DOT__m8__DOT__partial_products;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
