// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(484);
    // Setup sub module instances
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-12);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscopep_TOP = new VerilatedScope{this, "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER};
    __Vscopep_multiply_block = new VerilatedScope{this, "multiply_block", "multiply_block", "multiply_block", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8 = new VerilatedScope{this, "multiply_block.m8", "m8", "multiply8", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa13 = new VerilatedScope{this, "multiply_block.m8.fa13", "fa13", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa14 = new VerilatedScope{this, "multiply_block.m8.fa14", "fa14", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa15 = new VerilatedScope{this, "multiply_block.m8.fa15", "fa15", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa16 = new VerilatedScope{this, "multiply_block.m8.fa16", "fa16", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa17 = new VerilatedScope{this, "multiply_block.m8.fa17", "fa17", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa18 = new VerilatedScope{this, "multiply_block.m8.fa18", "fa18", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa19 = new VerilatedScope{this, "multiply_block.m8.fa19", "fa19", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa20 = new VerilatedScope{this, "multiply_block.m8.fa20", "fa20", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa21 = new VerilatedScope{this, "multiply_block.m8.fa21", "fa21", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa22 = new VerilatedScope{this, "multiply_block.m8.fa22", "fa22", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa23 = new VerilatedScope{this, "multiply_block.m8.fa23", "fa23", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa24 = new VerilatedScope{this, "multiply_block.m8.fa24", "fa24", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa25 = new VerilatedScope{this, "multiply_block.m8.fa25", "fa25", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa26 = new VerilatedScope{this, "multiply_block.m8.fa26", "fa26", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa27 = new VerilatedScope{this, "multiply_block.m8.fa27", "fa27", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa28 = new VerilatedScope{this, "multiply_block.m8.fa28", "fa28", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa29 = new VerilatedScope{this, "multiply_block.m8.fa29", "fa29", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa30 = new VerilatedScope{this, "multiply_block.m8.fa30", "fa30", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa31 = new VerilatedScope{this, "multiply_block.m8.fa31", "fa31", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa32 = new VerilatedScope{this, "multiply_block.m8.fa32", "fa32", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa33 = new VerilatedScope{this, "multiply_block.m8.fa33", "fa33", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa34 = new VerilatedScope{this, "multiply_block.m8.fa34", "fa34", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa35 = new VerilatedScope{this, "multiply_block.m8.fa35", "fa35", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa36 = new VerilatedScope{this, "multiply_block.m8.fa36", "fa36", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa37 = new VerilatedScope{this, "multiply_block.m8.fa37", "fa37", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa38 = new VerilatedScope{this, "multiply_block.m8.fa38", "fa38", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_1 = new VerilatedScope{this, "multiply_block.m8.fa_1", "fa_1", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_10 = new VerilatedScope{this, "multiply_block.m8.fa_10", "fa_10", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_11 = new VerilatedScope{this, "multiply_block.m8.fa_11", "fa_11", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_12 = new VerilatedScope{this, "multiply_block.m8.fa_12", "fa_12", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_2 = new VerilatedScope{this, "multiply_block.m8.fa_2", "fa_2", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_3 = new VerilatedScope{this, "multiply_block.m8.fa_3", "fa_3", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_4 = new VerilatedScope{this, "multiply_block.m8.fa_4", "fa_4", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_5 = new VerilatedScope{this, "multiply_block.m8.fa_5", "fa_5", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_6 = new VerilatedScope{this, "multiply_block.m8.fa_6", "fa_6", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_7 = new VerilatedScope{this, "multiply_block.m8.fa_7", "fa_7", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_8 = new VerilatedScope{this, "multiply_block.m8.fa_8", "fa_8", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__fa_9 = new VerilatedScope{this, "multiply_block.m8.fa_9", "fa_9", "full_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_1 = new VerilatedScope{this, "multiply_block.m8.ha_1", "ha_1", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_10 = new VerilatedScope{this, "multiply_block.m8.ha_10", "ha_10", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_11 = new VerilatedScope{this, "multiply_block.m8.ha_11", "ha_11", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_12 = new VerilatedScope{this, "multiply_block.m8.ha_12", "ha_12", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_13 = new VerilatedScope{this, "multiply_block.m8.ha_13", "ha_13", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_14 = new VerilatedScope{this, "multiply_block.m8.ha_14", "ha_14", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_15 = new VerilatedScope{this, "multiply_block.m8.ha_15", "ha_15", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_2 = new VerilatedScope{this, "multiply_block.m8.ha_2", "ha_2", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_3 = new VerilatedScope{this, "multiply_block.m8.ha_3", "ha_3", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_4 = new VerilatedScope{this, "multiply_block.m8.ha_4", "ha_4", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_5 = new VerilatedScope{this, "multiply_block.m8.ha_5", "ha_5", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_6 = new VerilatedScope{this, "multiply_block.m8.ha_6", "ha_6", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_7 = new VerilatedScope{this, "multiply_block.m8.ha_7", "ha_7", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_8 = new VerilatedScope{this, "multiply_block.m8.ha_8", "ha_8", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__ha_9 = new VerilatedScope{this, "multiply_block.m8.ha_9", "ha_9", "half_adder", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__m8__unnamedblk1 = new VerilatedScope{this, "multiply_block.m8.unnamedblk1", "unnamedblk1", "<null>", -12, VerilatedScope::SCOPE_OTHER};
    __Vscopep_multiply_block__m8__unnamedblk1__unnamedblk2 = new VerilatedScope{this, "multiply_block.m8.unnamedblk1.unnamedblk2", "unnamedblk2", "<null>", -12, VerilatedScope::SCOPE_OTHER};
    __Vscopep_multiply_block__s2u_inst = new VerilatedScope{this, "multiply_block.s2u_inst", "s2u_inst", "s2u", -12, VerilatedScope::SCOPE_MODULE};
    __Vscopep_multiply_block__u2s_inst = new VerilatedScope{this, "multiply_block.u2s_inst", "u2s_inst", "u2s", -12, VerilatedScope::SCOPE_MODULE};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_multiply_block);
    __Vhier.add(__Vscopep_multiply_block, __Vscopep_multiply_block__m8);
    __Vhier.add(__Vscopep_multiply_block, __Vscopep_multiply_block__s2u_inst);
    __Vhier.add(__Vscopep_multiply_block, __Vscopep_multiply_block__u2s_inst);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa13);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa14);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa15);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa16);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa17);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa18);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa19);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa20);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa21);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa22);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa23);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa24);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa25);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa26);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa27);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa28);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa29);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa30);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa31);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa32);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa33);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa34);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa35);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa36);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa37);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa38);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_1);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_10);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_11);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_12);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_2);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_3);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_4);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_5);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_6);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_7);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_8);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_9);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_1);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_10);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_11);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_12);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_13);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_14);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_15);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_2);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_3);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_4);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_5);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_6);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_7);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_8);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_9);
    __Vhier.add(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__unnamedblk1);
    __Vhier.add(__Vscopep_multiply_block__m8__unnamedblk1, __Vscopep_multiply_block__m8__unnamedblk1__unnamedblk2);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_TOP->varInsert("clk", &(TOP.clk), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("input_valid", &(TOP.input_valid), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("kernel_data", &(TOP.kernel_data), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("multiply_out", &(TOP.multiply_out), false, VLVT_UINT16, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_TOP->varInsert("output_valid", &(TOP.output_valid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("pixel_data", &(TOP.pixel_data), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("rst", &(TOP.rst), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("clk", &(TOP.multiply_block__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("input_valid", &(TOP.multiply_block__DOT__input_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("is_neg_1", &(TOP.multiply_block__DOT__is_neg_1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("is_neg_2", &(TOP.multiply_block__DOT__is_neg_2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("kernel_data", &(TOP.multiply_block__DOT__kernel_data), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block->varInsert("mo", &(TOP.multiply_block__DOT__mo), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_multiply_block->varInsert("multiply_out", &(TOP.multiply_block__DOT__multiply_out), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_multiply_block->varInsert("output_valid", &(TOP.multiply_block__DOT__output_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("pixel_data", &(TOP.multiply_block__DOT__pixel_data), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block->varInsert("rst", &(TOP.multiply_block__DOT__rst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block->varInsert("s2u_to_mult8", &(TOP.multiply_block__DOT__s2u_to_mult8), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("clk", &(TOP.multiply_block__DOT__m8__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("in_valid", &(TOP.multiply_block__DOT__m8__DOT__in_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("is_neg_in", &(TOP.multiply_block__DOT__m8__DOT__is_neg_in), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("is_neg_out", &(TOP.multiply_block__DOT__m8__DOT__is_neg_out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("out", &(TOP.multiply_block__DOT__m8__DOT__out), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_multiply_block__m8->varInsert("output_valid", &(TOP.multiply_block__DOT__m8__DOT__output_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("partial_products", &(TOP.multiply_block__DOT__m8__DOT__partial_products), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 2, 0 ,0,7 ,0,7);
    __Vscopep_multiply_block__m8->varInsert("r1", &(TOP.multiply_block__DOT__m8__DOT__r1), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("r1_temp", &(TOP.multiply_block__DOT__m8__DOT__r1_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("r2", &(TOP.multiply_block__DOT__m8__DOT__r2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r2_temp", &(TOP.multiply_block__DOT__m8__DOT__r2_temp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r3", &(TOP.multiply_block__DOT__m8__DOT__r3), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("r3_temp", &(TOP.multiply_block__DOT__m8__DOT__r3_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("r4", &(TOP.multiply_block__DOT__m8__DOT__r4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r4_temp", &(TOP.multiply_block__DOT__m8__DOT__r4_temp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r5", &(TOP.multiply_block__DOT__m8__DOT__r5), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r5_temp", &(TOP.multiply_block__DOT__m8__DOT__r5_temp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r6", &(TOP.multiply_block__DOT__m8__DOT__r6), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("r6_temp", &(TOP.multiply_block__DOT__m8__DOT__r6_temp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("rst", &(TOP.multiply_block__DOT__m8__DOT__rst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("s1", &(TOP.multiply_block__DOT__m8__DOT__s1), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,10,0);
    __Vscopep_multiply_block__m8->varInsert("s1_temp", &(TOP.multiply_block__DOT__m8__DOT__s1_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,10,0);
    __Vscopep_multiply_block__m8->varInsert("s2", &(TOP.multiply_block__DOT__m8__DOT__s2), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("s2_temp", &(TOP.multiply_block__DOT__m8__DOT__s2_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("s3", &(TOP.multiply_block__DOT__m8__DOT__s3), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("s3_temp", &(TOP.multiply_block__DOT__m8__DOT__s3_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("s4", &(TOP.multiply_block__DOT__m8__DOT__s4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("s4_temp", &(TOP.multiply_block__DOT__m8__DOT__s4_temp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("stage_five_valid", &(TOP.multiply_block__DOT__m8__DOT__stage_five_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("stage_four_valid", &(TOP.multiply_block__DOT__m8__DOT__stage_four_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("stage_one_valid", &(TOP.multiply_block__DOT__m8__DOT__stage_one_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("stage_three_valid", &(TOP.multiply_block__DOT__m8__DOT__stage_three_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("stage_two_valid", &(TOP.multiply_block__DOT__m8__DOT__stage_two_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("sum_temp", &(TOP.multiply_block__DOT__m8__DOT__sum_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,15,0);
    __Vscopep_multiply_block__m8->varInsert("t1", &(TOP.multiply_block__DOT__m8__DOT__t1), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,13,0);
    __Vscopep_multiply_block__m8->varInsert("t1_temp", &(TOP.multiply_block__DOT__m8__DOT__t1_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,13,0);
    __Vscopep_multiply_block__m8->varInsert("t2", &(TOP.multiply_block__DOT__m8__DOT__t2), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,10,0);
    __Vscopep_multiply_block__m8->varInsert("t2_temp", &(TOP.multiply_block__DOT__m8__DOT__t2_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,10,0);
    __Vscopep_multiply_block__m8->varInsert("t3", &(TOP.multiply_block__DOT__m8__DOT__t3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("t3_temp", &(TOP.multiply_block__DOT__m8__DOT__t3_temp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_multiply_block__m8->varInsert("u1", &(TOP.multiply_block__DOT__m8__DOT__u1), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_multiply_block__m8->varInsert("u1_temp", &(TOP.multiply_block__DOT__m8__DOT__u1_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,15,0);
    __Vscopep_multiply_block__m8->varInsert("u2", &(TOP.multiply_block__DOT__m8__DOT__u2), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("u2_temp", &(TOP.multiply_block__DOT__m8__DOT__u2_temp), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,9,0);
    __Vscopep_multiply_block__m8->varInsert("x1", &(TOP.multiply_block__DOT__m8__DOT__x1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("x2", &(TOP.multiply_block__DOT__m8__DOT__x2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("x3", &(TOP.multiply_block__DOT__m8__DOT__x3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("x4", &(TOP.multiply_block__DOT__m8__DOT__x4), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8->varInsert("x5", &(TOP.multiply_block__DOT__m8__DOT__x5), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa13->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa13__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa13->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa13__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa13->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa13__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa13->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa13__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa13->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa13__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa14->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa14__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa14->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa14__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa14->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa14__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa14->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa14__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa14->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa14__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa15->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa15__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa15->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa15__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa15->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa15__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa15->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa15__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa15->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa15__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa16->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa16__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa16->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa16__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa16->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa16__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa16->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa16__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa16->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa16__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa17->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa17__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa17->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa17__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa17->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa17__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa17->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa17__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa17->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa17__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa18->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa18__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa18->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa18__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa18->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa18__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa18->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa18__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa18->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa18__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa19->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa19__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa19->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa19__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa19->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa19__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa19->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa19__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa19->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa19__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa20->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa20__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa20->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa20__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa20->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa20__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa20->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa20__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa20->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa20__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa21->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa21__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa21->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa21__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa21->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa21__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa21->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa21__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa21->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa21__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa22->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa22__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa22->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa22__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa22->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa22__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa22->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa22__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa22->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa22__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa23->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa23__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa23->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa23__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa23->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa23__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa23->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa23__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa23->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa23__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa24->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa24__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa24->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa24__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa24->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa24__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa24->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa24__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa24->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa24__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa25->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa25__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa25->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa25__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa25->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa25__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa25->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa25__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa25->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa25__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa26->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa26__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa26->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa26__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa26->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa26__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa26->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa26__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa26->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa26__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa27->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa27__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa27->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa27__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa27->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa27__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa27->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa27__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa27->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa27__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa28->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa28__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa28->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa28__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa28->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa28__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa28->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa28__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa28->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa28__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa29->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa29__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa29->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa29__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa29->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa29__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa29->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa29__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa29->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa29__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa30->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa30__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa30->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa30__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa30->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa30__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa30->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa30__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa30->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa30__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa31->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa31__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa31->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa31__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa31->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa31__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa31->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa31__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa31->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa31__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa32->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa32__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa32->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa32__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa32->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa32__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa32->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa32__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa32->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa32__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa33->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa33__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa33->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa33__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa33->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa33__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa33->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa33__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa33->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa33__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa34->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa34__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa34->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa34__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa34->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa34__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa34->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa34__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa34->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa34__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa35->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa35__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa35->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa35__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa35->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa35__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa35->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa35__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa35->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa35__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa36->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa36__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa36->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa36__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa36->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa36__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa36->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa36__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa36->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa36__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa37->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa37__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa37->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa37__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa37->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa37__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa37->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa37__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa37->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa37__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa38->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa38__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa38->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa38__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa38->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa38__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa38->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa38__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa38->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa38__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_1->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_1__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_1->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_1__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_1->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_1__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_1->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_1__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_1->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_1__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_10->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_10__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_10->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_10__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_10->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_10__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_10->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_10__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_10->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_10__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_11->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_11__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_11->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_11__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_11->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_11__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_11->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_11__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_11->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_11__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_12->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_12__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_12->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_12__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_12->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_12__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_12->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_12__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_12->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_12__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_2->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_2__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_2->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_2__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_2->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_2__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_2->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_2__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_2->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_2__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_3->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_3__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_3->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_3__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_3->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_3__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_3->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_3__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_3->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_3__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_4->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_4__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_4->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_4__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_4->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_4__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_4->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_4__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_4->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_4__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_5->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_5__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_5->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_5__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_5->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_5__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_5->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_5__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_5->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_5__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_6->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_6__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_6->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_6__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_6->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_6__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_6->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_6__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_6->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_6__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_7->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_7__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_7->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_7__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_7->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_7__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_7->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_7__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_7->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_7__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_8->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_8__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_8->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_8__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_8->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_8__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_8->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_8__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_8->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_8__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_9->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__fa_9__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_9->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__fa_9__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_9->varInsert("cin", &(TOP.multiply_block__DOT__m8__DOT__fa_9__DOT__cin), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__fa_9->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__fa_9__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__fa_9->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__fa_9__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_1->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_1__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_1->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_1__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_1->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_1__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_1->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_1__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_10->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_10__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_10->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_10__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_10->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_10__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_10->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_10__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_11->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_11__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_11->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_11__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_11->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_11__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_11->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_11__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_12->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_12__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_12->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_12__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_12->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_12__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_12->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_12__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_13->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_13__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_13->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_13__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_13->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_13__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_13->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_13__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_14->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_14__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_14->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_14__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_14->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_14__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_14->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_14__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_15->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_15__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_15->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_15__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_15->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_15__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_15->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_15__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_2->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_2__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_2->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_2__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_2->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_2__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_2->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_2__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_3->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_3__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_3->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_3__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_3->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_3__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_3->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_3__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_4->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_4__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_4->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_4__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_4->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_4__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_4->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_4__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_5->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_5__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_5->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_5__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_5->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_5__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_5->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_5__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_6->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_6__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_6->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_6__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_6->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_6__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_6->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_6__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_7->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_7__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_7->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_7__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_7->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_7__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_7->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_7__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_8->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_8__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_8->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_8__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_8->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_8__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_8->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_8__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_9->varInsert("a", &(TOP.multiply_block__DOT__m8__DOT__ha_9__DOT__a), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_9->varInsert("b", &(TOP.multiply_block__DOT__m8__DOT__ha_9__DOT__b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__m8__ha_9->varInsert("cout", &(TOP.multiply_block__DOT__m8__DOT__ha_9__DOT__cout), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__ha_9->varInsert("s", &(TOP.multiply_block__DOT__m8__DOT__ha_9__DOT__s), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_multiply_block__m8__unnamedblk1->varInsert("i", &(TOP.multiply_block__DOT__m8__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_multiply_block__m8__unnamedblk1__unnamedblk2->varInsert("j", &(TOP.multiply_block__DOT__m8__DOT__unnamedblk1__DOT__unnamedblk2__DOT__j), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_multiply_block__s2u_inst->varInsert("in", &(TOP.multiply_block__DOT__s2u_inst__DOT__in), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__s2u_inst->varInsert("is_neg", &(TOP.multiply_block__DOT__s2u_inst__DOT__is_neg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__s2u_inst->varInsert("out", &(TOP.multiply_block__DOT__s2u_inst__DOT__out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_multiply_block__u2s_inst->varInsert("in", &(TOP.multiply_block__DOT__u2s_inst__DOT__in), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_multiply_block__u2s_inst->varInsert("is_neg", &(TOP.multiply_block__DOT__u2s_inst__DOT__is_neg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_multiply_block__u2s_inst->varInsert("out", &(TOP.multiply_block__DOT__u2s_inst__DOT__out), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_multiply_block);
    __Vhier.remove(__Vscopep_multiply_block, __Vscopep_multiply_block__m8);
    __Vhier.remove(__Vscopep_multiply_block, __Vscopep_multiply_block__s2u_inst);
    __Vhier.remove(__Vscopep_multiply_block, __Vscopep_multiply_block__u2s_inst);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa13);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa14);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa15);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa16);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa17);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa18);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa19);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa20);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa21);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa22);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa23);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa24);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa25);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa26);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa27);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa28);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa29);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa30);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa31);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa32);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa33);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa34);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa35);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa36);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa37);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa38);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_1);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_10);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_11);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_12);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_2);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_3);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_4);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_5);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_6);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_7);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_8);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__fa_9);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_1);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_10);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_11);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_12);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_13);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_14);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_15);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_2);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_3);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_4);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_5);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_6);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_7);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_8);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__ha_9);
    __Vhier.remove(__Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8__unnamedblk1);
    __Vhier.remove(__Vscopep_multiply_block__m8__unnamedblk1, __Vscopep_multiply_block__m8__unnamedblk1__unnamedblk2);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_TOP, __Vscopep_TOP = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block, __Vscopep_multiply_block = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8, __Vscopep_multiply_block__m8 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa13, __Vscopep_multiply_block__m8__fa13 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa14, __Vscopep_multiply_block__m8__fa14 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa15, __Vscopep_multiply_block__m8__fa15 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa16, __Vscopep_multiply_block__m8__fa16 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa17, __Vscopep_multiply_block__m8__fa17 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa18, __Vscopep_multiply_block__m8__fa18 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa19, __Vscopep_multiply_block__m8__fa19 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa20, __Vscopep_multiply_block__m8__fa20 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa21, __Vscopep_multiply_block__m8__fa21 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa22, __Vscopep_multiply_block__m8__fa22 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa23, __Vscopep_multiply_block__m8__fa23 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa24, __Vscopep_multiply_block__m8__fa24 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa25, __Vscopep_multiply_block__m8__fa25 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa26, __Vscopep_multiply_block__m8__fa26 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa27, __Vscopep_multiply_block__m8__fa27 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa28, __Vscopep_multiply_block__m8__fa28 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa29, __Vscopep_multiply_block__m8__fa29 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa30, __Vscopep_multiply_block__m8__fa30 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa31, __Vscopep_multiply_block__m8__fa31 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa32, __Vscopep_multiply_block__m8__fa32 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa33, __Vscopep_multiply_block__m8__fa33 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa34, __Vscopep_multiply_block__m8__fa34 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa35, __Vscopep_multiply_block__m8__fa35 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa36, __Vscopep_multiply_block__m8__fa36 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa37, __Vscopep_multiply_block__m8__fa37 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa38, __Vscopep_multiply_block__m8__fa38 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_1, __Vscopep_multiply_block__m8__fa_1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_10, __Vscopep_multiply_block__m8__fa_10 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_11, __Vscopep_multiply_block__m8__fa_11 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_12, __Vscopep_multiply_block__m8__fa_12 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_2, __Vscopep_multiply_block__m8__fa_2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_3, __Vscopep_multiply_block__m8__fa_3 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_4, __Vscopep_multiply_block__m8__fa_4 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_5, __Vscopep_multiply_block__m8__fa_5 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_6, __Vscopep_multiply_block__m8__fa_6 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_7, __Vscopep_multiply_block__m8__fa_7 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_8, __Vscopep_multiply_block__m8__fa_8 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__fa_9, __Vscopep_multiply_block__m8__fa_9 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_1, __Vscopep_multiply_block__m8__ha_1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_10, __Vscopep_multiply_block__m8__ha_10 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_11, __Vscopep_multiply_block__m8__ha_11 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_12, __Vscopep_multiply_block__m8__ha_12 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_13, __Vscopep_multiply_block__m8__ha_13 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_14, __Vscopep_multiply_block__m8__ha_14 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_15, __Vscopep_multiply_block__m8__ha_15 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_2, __Vscopep_multiply_block__m8__ha_2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_3, __Vscopep_multiply_block__m8__ha_3 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_4, __Vscopep_multiply_block__m8__ha_4 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_5, __Vscopep_multiply_block__m8__ha_5 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_6, __Vscopep_multiply_block__m8__ha_6 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_7, __Vscopep_multiply_block__m8__ha_7 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_8, __Vscopep_multiply_block__m8__ha_8 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__ha_9, __Vscopep_multiply_block__m8__ha_9 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__unnamedblk1, __Vscopep_multiply_block__m8__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__m8__unnamedblk1__unnamedblk2, __Vscopep_multiply_block__m8__unnamedblk1__unnamedblk2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__s2u_inst, __Vscopep_multiply_block__s2u_inst = nullptr);
    VL_DO_CLEAR(delete __Vscopep_multiply_block__u2s_inst, __Vscopep_multiply_block__u2s_inst = nullptr);
    // Tear down sub module instances
}
