// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+0,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+1,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"pixel_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+3,0,"kernel_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+4,0,"input_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"output_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+6,0,"multiply_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->popPrefix();
    tracep->pushPrefix("multiply_block", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+7,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+8,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+9,0,"pixel_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+10,0,"kernel_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+11,0,"input_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"output_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+13,0,"multiply_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+14,0,"s2u_to_mult8",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+15,0,"is_neg_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"is_neg_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+17,0,"mo",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("m8", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+18,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+19,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"is_neg_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"is_neg_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+23,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+24,0,"in_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+25,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+26,0,"output_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+27,0,"x1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"x2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"x3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"x4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"x5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"stage_one_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+33,0,"r1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+34,0,"r1_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+35,0,"r2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+36,0,"r2_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+37,0,"r3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+38,0,"r3_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+39,0,"r4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+40,0,"r4_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+41,0,"r5",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+42,0,"r5_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+43,0,"r6",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+44,0,"r6_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+45,0,"stage_two_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+46,0,"s1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+47,0,"s1_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+48,0,"s2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+49,0,"s2_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+50,0,"s3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+51,0,"s3_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+52,0,"s4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+53,0,"s4_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+54,0,"stage_three_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+55,0,"t1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBus(c+56,0,"t1_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBus(c+57,0,"t2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+58,0,"t2_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 10,0);
    tracep->declBus(c+59,0,"t3",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+60,0,"t3_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+61,0,"stage_four_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+62,0,"u1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+63,0,"u1_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+64,0,"u2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+65,0,"u2_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+66,0,"stage_five_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+67,0,"sum_temp",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("fa13", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+68,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+71,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa14", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+73,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+77,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa15", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+78,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+79,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+80,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+81,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa16", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+83,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+85,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+86,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+87,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa17", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+88,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+91,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa18", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+93,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa19", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+98,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+101,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa20", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+103,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+104,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+106,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa21", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+108,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+109,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa22", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+113,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa23", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+118,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa24", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+123,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa25", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+128,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa26", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+133,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa27", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+138,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa28", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+143,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa29", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+148,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa30", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+153,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa31", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+158,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa32", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+163,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa33", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+168,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+169,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa34", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+173,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa35", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+178,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+179,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+180,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+181,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa36", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+183,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+184,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+185,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+186,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+187,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa37", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+188,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+189,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+190,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+191,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+192,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa38", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+193,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+194,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+195,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+198,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+199,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+200,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+201,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+202,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+203,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+204,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+205,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+206,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+207,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+208,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+209,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+210,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+211,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+212,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_12", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+213,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+214,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+216,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+217,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+218,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+223,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+228,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+232,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_5", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+233,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+234,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+236,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+237,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_6", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+238,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+239,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+242,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_7", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+243,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+244,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_8", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+248,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+249,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+250,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+251,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+252,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("fa_9", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+253,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+255,0,"cin",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+256,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+258,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+259,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+260,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+261,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+262,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+263,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+264,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+265,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+266,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+268,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+269,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_12", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+270,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+271,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+272,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+273,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_13", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+274,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+275,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+277,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_14", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+278,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+279,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+280,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+281,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_15", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+282,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+283,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+284,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+285,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+286,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+287,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+288,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+289,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+290,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+291,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+292,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+293,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+294,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+295,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+296,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+297,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_5", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+298,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+299,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+300,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+301,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_6", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+302,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+303,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+304,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+305,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_7", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+306,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+307,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+308,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+309,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_8", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+310,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+311,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+312,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+313,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("ha_9", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+314,0,"a",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+315,0,"b",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+316,0,"s",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+317,0,"cout",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+318,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->pushPrefix("unnamedblk2", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+319,0,"j",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("s2u_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+320,0,"in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+321,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+322,0,"is_neg",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("u2s_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+323,0,"in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+324,0,"is_neg",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+325,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Body
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+0,(vlSelfRef.clk));
    bufp->fullBit(oldp+1,(vlSelfRef.rst));
    bufp->fullCData(oldp+2,(vlSelfRef.pixel_data),8);
    bufp->fullCData(oldp+3,(vlSelfRef.kernel_data),8);
    bufp->fullBit(oldp+4,(vlSelfRef.input_valid));
    bufp->fullBit(oldp+5,(vlSelfRef.output_valid));
    bufp->fullSData(oldp+6,(vlSelfRef.multiply_out),16);
    bufp->fullBit(oldp+7,(vlSelfRef.multiply_block__DOT__clk));
    bufp->fullBit(oldp+8,(vlSelfRef.multiply_block__DOT__rst));
    bufp->fullCData(oldp+9,(vlSelfRef.multiply_block__DOT__pixel_data),8);
    bufp->fullCData(oldp+10,(vlSelfRef.multiply_block__DOT__kernel_data),8);
    bufp->fullBit(oldp+11,(vlSelfRef.multiply_block__DOT__input_valid));
    bufp->fullBit(oldp+12,(vlSelfRef.multiply_block__DOT__output_valid));
    bufp->fullSData(oldp+13,(vlSelfRef.multiply_block__DOT__multiply_out),16);
    bufp->fullCData(oldp+14,(vlSelfRef.multiply_block__DOT__s2u_to_mult8),8);
    bufp->fullBit(oldp+15,(vlSelfRef.multiply_block__DOT__is_neg_1));
    bufp->fullBit(oldp+16,(vlSelfRef.multiply_block__DOT__is_neg_2));
    bufp->fullSData(oldp+17,(vlSelfRef.multiply_block__DOT__mo),16);
    bufp->fullBit(oldp+18,(vlSelfRef.multiply_block__DOT__m8__DOT__clk));
    bufp->fullBit(oldp+19,(vlSelfRef.multiply_block__DOT__m8__DOT__rst));
    bufp->fullBit(oldp+20,(vlSelfRef.multiply_block__DOT__m8__DOT__is_neg_in));
    bufp->fullBit(oldp+21,(vlSelfRef.multiply_block__DOT__m8__DOT__is_neg_out));
    bufp->fullCData(oldp+22,(vlSelfRef.multiply_block__DOT__m8__DOT__a),8);
    bufp->fullCData(oldp+23,(vlSelfRef.multiply_block__DOT__m8__DOT__b),8);
    bufp->fullBit(oldp+24,(vlSelfRef.multiply_block__DOT__m8__DOT__in_valid));
    bufp->fullSData(oldp+25,(vlSelfRef.multiply_block__DOT__m8__DOT__out),16);
    bufp->fullBit(oldp+26,(vlSelfRef.multiply_block__DOT__m8__DOT__output_valid));
    bufp->fullBit(oldp+27,(vlSelfRef.multiply_block__DOT__m8__DOT__x1));
    bufp->fullBit(oldp+28,(vlSelfRef.multiply_block__DOT__m8__DOT__x2));
    bufp->fullBit(oldp+29,(vlSelfRef.multiply_block__DOT__m8__DOT__x3));
    bufp->fullBit(oldp+30,(vlSelfRef.multiply_block__DOT__m8__DOT__x4));
    bufp->fullBit(oldp+31,(vlSelfRef.multiply_block__DOT__m8__DOT__x5));
    bufp->fullBit(oldp+32,(vlSelfRef.multiply_block__DOT__m8__DOT__stage_one_valid));
    bufp->fullSData(oldp+33,(vlSelfRef.multiply_block__DOT__m8__DOT__r1),10);
    bufp->fullSData(oldp+34,(vlSelfRef.multiply_block__DOT__m8__DOT__r1_temp),10);
    bufp->fullCData(oldp+35,(vlSelfRef.multiply_block__DOT__m8__DOT__r2),8);
    bufp->fullCData(oldp+36,(vlSelfRef.multiply_block__DOT__m8__DOT__r2_temp),8);
    bufp->fullSData(oldp+37,(vlSelfRef.multiply_block__DOT__m8__DOT__r3),10);
    bufp->fullSData(oldp+38,(vlSelfRef.multiply_block__DOT__m8__DOT__r3_temp),10);
    bufp->fullCData(oldp+39,(vlSelfRef.multiply_block__DOT__m8__DOT__r4),8);
    bufp->fullCData(oldp+40,(vlSelfRef.multiply_block__DOT__m8__DOT__r4_temp),8);
    bufp->fullCData(oldp+41,(vlSelfRef.multiply_block__DOT__m8__DOT__r5),8);
    bufp->fullCData(oldp+42,(vlSelfRef.multiply_block__DOT__m8__DOT__r5_temp),8);
    bufp->fullCData(oldp+43,(vlSelfRef.multiply_block__DOT__m8__DOT__r6),8);
    bufp->fullCData(oldp+44,(vlSelfRef.multiply_block__DOT__m8__DOT__r6_temp),8);
    bufp->fullBit(oldp+45,(vlSelfRef.multiply_block__DOT__m8__DOT__stage_two_valid));
    bufp->fullSData(oldp+46,(vlSelfRef.multiply_block__DOT__m8__DOT__s1),11);
    bufp->fullSData(oldp+47,(vlSelfRef.multiply_block__DOT__m8__DOT__s1_temp),11);
    bufp->fullSData(oldp+48,(vlSelfRef.multiply_block__DOT__m8__DOT__s2),10);
    bufp->fullSData(oldp+49,(vlSelfRef.multiply_block__DOT__m8__DOT__s2_temp),10);
    bufp->fullSData(oldp+50,(vlSelfRef.multiply_block__DOT__m8__DOT__s3),10);
    bufp->fullSData(oldp+51,(vlSelfRef.multiply_block__DOT__m8__DOT__s3_temp),10);
    bufp->fullCData(oldp+52,(vlSelfRef.multiply_block__DOT__m8__DOT__s4),8);
    bufp->fullCData(oldp+53,(vlSelfRef.multiply_block__DOT__m8__DOT__s4_temp),8);
    bufp->fullBit(oldp+54,(vlSelfRef.multiply_block__DOT__m8__DOT__stage_three_valid));
    bufp->fullSData(oldp+55,(vlSelfRef.multiply_block__DOT__m8__DOT__t1),14);
    bufp->fullSData(oldp+56,(vlSelfRef.multiply_block__DOT__m8__DOT__t1_temp),14);
    bufp->fullSData(oldp+57,(vlSelfRef.multiply_block__DOT__m8__DOT__t2),11);
    bufp->fullSData(oldp+58,(vlSelfRef.multiply_block__DOT__m8__DOT__t2_temp),11);
    bufp->fullCData(oldp+59,(vlSelfRef.multiply_block__DOT__m8__DOT__t3),8);
    bufp->fullCData(oldp+60,(vlSelfRef.multiply_block__DOT__m8__DOT__t3_temp),8);
    bufp->fullBit(oldp+61,(vlSelfRef.multiply_block__DOT__m8__DOT__stage_four_valid));
    bufp->fullSData(oldp+62,(vlSelfRef.multiply_block__DOT__m8__DOT__u1),16);
    bufp->fullSData(oldp+63,(vlSelfRef.multiply_block__DOT__m8__DOT__u1_temp),16);
    bufp->fullSData(oldp+64,(vlSelfRef.multiply_block__DOT__m8__DOT__u2),10);
    bufp->fullSData(oldp+65,(vlSelfRef.multiply_block__DOT__m8__DOT__u2_temp),10);
    bufp->fullBit(oldp+66,(vlSelfRef.multiply_block__DOT__m8__DOT__stage_five_valid));
    bufp->fullSData(oldp+67,(vlSelfRef.multiply_block__DOT__m8__DOT__sum_temp),16);
    bufp->fullBit(oldp+68,(vlSelfRef.multiply_block__DOT__m8__DOT__fa13__DOT__a));
    bufp->fullBit(oldp+69,(vlSelfRef.multiply_block__DOT__m8__DOT__fa13__DOT__b));
    bufp->fullBit(oldp+70,(vlSelfRef.multiply_block__DOT__m8__DOT__fa13__DOT__cin));
    bufp->fullBit(oldp+71,(vlSelfRef.multiply_block__DOT__m8__DOT__fa13__DOT__s));
    bufp->fullBit(oldp+72,(vlSelfRef.multiply_block__DOT__m8__DOT__fa13__DOT__cout));
    bufp->fullBit(oldp+73,(vlSelfRef.multiply_block__DOT__m8__DOT__fa14__DOT__a));
    bufp->fullBit(oldp+74,(vlSelfRef.multiply_block__DOT__m8__DOT__fa14__DOT__b));
    bufp->fullBit(oldp+75,(vlSelfRef.multiply_block__DOT__m8__DOT__fa14__DOT__cin));
    bufp->fullBit(oldp+76,(vlSelfRef.multiply_block__DOT__m8__DOT__fa14__DOT__s));
    bufp->fullBit(oldp+77,(vlSelfRef.multiply_block__DOT__m8__DOT__fa14__DOT__cout));
    bufp->fullBit(oldp+78,(vlSelfRef.multiply_block__DOT__m8__DOT__fa15__DOT__a));
    bufp->fullBit(oldp+79,(vlSelfRef.multiply_block__DOT__m8__DOT__fa15__DOT__b));
    bufp->fullBit(oldp+80,(vlSelfRef.multiply_block__DOT__m8__DOT__fa15__DOT__cin));
    bufp->fullBit(oldp+81,(vlSelfRef.multiply_block__DOT__m8__DOT__fa15__DOT__s));
    bufp->fullBit(oldp+82,(vlSelfRef.multiply_block__DOT__m8__DOT__fa15__DOT__cout));
    bufp->fullBit(oldp+83,(vlSelfRef.multiply_block__DOT__m8__DOT__fa16__DOT__a));
    bufp->fullBit(oldp+84,(vlSelfRef.multiply_block__DOT__m8__DOT__fa16__DOT__b));
    bufp->fullBit(oldp+85,(vlSelfRef.multiply_block__DOT__m8__DOT__fa16__DOT__cin));
    bufp->fullBit(oldp+86,(vlSelfRef.multiply_block__DOT__m8__DOT__fa16__DOT__s));
    bufp->fullBit(oldp+87,(vlSelfRef.multiply_block__DOT__m8__DOT__fa16__DOT__cout));
    bufp->fullBit(oldp+88,(vlSelfRef.multiply_block__DOT__m8__DOT__fa17__DOT__a));
    bufp->fullBit(oldp+89,(vlSelfRef.multiply_block__DOT__m8__DOT__fa17__DOT__b));
    bufp->fullBit(oldp+90,(vlSelfRef.multiply_block__DOT__m8__DOT__fa17__DOT__cin));
    bufp->fullBit(oldp+91,(vlSelfRef.multiply_block__DOT__m8__DOT__fa17__DOT__s));
    bufp->fullBit(oldp+92,(vlSelfRef.multiply_block__DOT__m8__DOT__fa17__DOT__cout));
    bufp->fullBit(oldp+93,(vlSelfRef.multiply_block__DOT__m8__DOT__fa18__DOT__a));
    bufp->fullBit(oldp+94,(vlSelfRef.multiply_block__DOT__m8__DOT__fa18__DOT__b));
    bufp->fullBit(oldp+95,(vlSelfRef.multiply_block__DOT__m8__DOT__fa18__DOT__cin));
    bufp->fullBit(oldp+96,(vlSelfRef.multiply_block__DOT__m8__DOT__fa18__DOT__s));
    bufp->fullBit(oldp+97,(vlSelfRef.multiply_block__DOT__m8__DOT__fa18__DOT__cout));
    bufp->fullBit(oldp+98,(vlSelfRef.multiply_block__DOT__m8__DOT__fa19__DOT__a));
    bufp->fullBit(oldp+99,(vlSelfRef.multiply_block__DOT__m8__DOT__fa19__DOT__b));
    bufp->fullBit(oldp+100,(vlSelfRef.multiply_block__DOT__m8__DOT__fa19__DOT__cin));
    bufp->fullBit(oldp+101,(vlSelfRef.multiply_block__DOT__m8__DOT__fa19__DOT__s));
    bufp->fullBit(oldp+102,(vlSelfRef.multiply_block__DOT__m8__DOT__fa19__DOT__cout));
    bufp->fullBit(oldp+103,(vlSelfRef.multiply_block__DOT__m8__DOT__fa20__DOT__a));
    bufp->fullBit(oldp+104,(vlSelfRef.multiply_block__DOT__m8__DOT__fa20__DOT__b));
    bufp->fullBit(oldp+105,(vlSelfRef.multiply_block__DOT__m8__DOT__fa20__DOT__cin));
    bufp->fullBit(oldp+106,(vlSelfRef.multiply_block__DOT__m8__DOT__fa20__DOT__s));
    bufp->fullBit(oldp+107,(vlSelfRef.multiply_block__DOT__m8__DOT__fa20__DOT__cout));
    bufp->fullBit(oldp+108,(vlSelfRef.multiply_block__DOT__m8__DOT__fa21__DOT__a));
    bufp->fullBit(oldp+109,(vlSelfRef.multiply_block__DOT__m8__DOT__fa21__DOT__b));
    bufp->fullBit(oldp+110,(vlSelfRef.multiply_block__DOT__m8__DOT__fa21__DOT__cin));
    bufp->fullBit(oldp+111,(vlSelfRef.multiply_block__DOT__m8__DOT__fa21__DOT__s));
    bufp->fullBit(oldp+112,(vlSelfRef.multiply_block__DOT__m8__DOT__fa21__DOT__cout));
    bufp->fullBit(oldp+113,(vlSelfRef.multiply_block__DOT__m8__DOT__fa22__DOT__a));
    bufp->fullBit(oldp+114,(vlSelfRef.multiply_block__DOT__m8__DOT__fa22__DOT__b));
    bufp->fullBit(oldp+115,(vlSelfRef.multiply_block__DOT__m8__DOT__fa22__DOT__cin));
    bufp->fullBit(oldp+116,(vlSelfRef.multiply_block__DOT__m8__DOT__fa22__DOT__s));
    bufp->fullBit(oldp+117,(vlSelfRef.multiply_block__DOT__m8__DOT__fa22__DOT__cout));
    bufp->fullBit(oldp+118,(vlSelfRef.multiply_block__DOT__m8__DOT__fa23__DOT__a));
    bufp->fullBit(oldp+119,(vlSelfRef.multiply_block__DOT__m8__DOT__fa23__DOT__b));
    bufp->fullBit(oldp+120,(vlSelfRef.multiply_block__DOT__m8__DOT__fa23__DOT__cin));
    bufp->fullBit(oldp+121,(vlSelfRef.multiply_block__DOT__m8__DOT__fa23__DOT__s));
    bufp->fullBit(oldp+122,(vlSelfRef.multiply_block__DOT__m8__DOT__fa23__DOT__cout));
    bufp->fullBit(oldp+123,(vlSelfRef.multiply_block__DOT__m8__DOT__fa24__DOT__a));
    bufp->fullBit(oldp+124,(vlSelfRef.multiply_block__DOT__m8__DOT__fa24__DOT__b));
    bufp->fullBit(oldp+125,(vlSelfRef.multiply_block__DOT__m8__DOT__fa24__DOT__cin));
    bufp->fullBit(oldp+126,(vlSelfRef.multiply_block__DOT__m8__DOT__fa24__DOT__s));
    bufp->fullBit(oldp+127,(vlSelfRef.multiply_block__DOT__m8__DOT__fa24__DOT__cout));
    bufp->fullBit(oldp+128,(vlSelfRef.multiply_block__DOT__m8__DOT__fa25__DOT__a));
    bufp->fullBit(oldp+129,(vlSelfRef.multiply_block__DOT__m8__DOT__fa25__DOT__b));
    bufp->fullBit(oldp+130,(vlSelfRef.multiply_block__DOT__m8__DOT__fa25__DOT__cin));
    bufp->fullBit(oldp+131,(vlSelfRef.multiply_block__DOT__m8__DOT__fa25__DOT__s));
    bufp->fullBit(oldp+132,(vlSelfRef.multiply_block__DOT__m8__DOT__fa25__DOT__cout));
    bufp->fullBit(oldp+133,(vlSelfRef.multiply_block__DOT__m8__DOT__fa26__DOT__a));
    bufp->fullBit(oldp+134,(vlSelfRef.multiply_block__DOT__m8__DOT__fa26__DOT__b));
    bufp->fullBit(oldp+135,(vlSelfRef.multiply_block__DOT__m8__DOT__fa26__DOT__cin));
    bufp->fullBit(oldp+136,(vlSelfRef.multiply_block__DOT__m8__DOT__fa26__DOT__s));
    bufp->fullBit(oldp+137,(vlSelfRef.multiply_block__DOT__m8__DOT__fa26__DOT__cout));
    bufp->fullBit(oldp+138,(vlSelfRef.multiply_block__DOT__m8__DOT__fa27__DOT__a));
    bufp->fullBit(oldp+139,(vlSelfRef.multiply_block__DOT__m8__DOT__fa27__DOT__b));
    bufp->fullBit(oldp+140,(vlSelfRef.multiply_block__DOT__m8__DOT__fa27__DOT__cin));
    bufp->fullBit(oldp+141,(vlSelfRef.multiply_block__DOT__m8__DOT__fa27__DOT__s));
    bufp->fullBit(oldp+142,(vlSelfRef.multiply_block__DOT__m8__DOT__fa27__DOT__cout));
    bufp->fullBit(oldp+143,(vlSelfRef.multiply_block__DOT__m8__DOT__fa28__DOT__a));
    bufp->fullBit(oldp+144,(vlSelfRef.multiply_block__DOT__m8__DOT__fa28__DOT__b));
    bufp->fullBit(oldp+145,(vlSelfRef.multiply_block__DOT__m8__DOT__fa28__DOT__cin));
    bufp->fullBit(oldp+146,(vlSelfRef.multiply_block__DOT__m8__DOT__fa28__DOT__s));
    bufp->fullBit(oldp+147,(vlSelfRef.multiply_block__DOT__m8__DOT__fa28__DOT__cout));
    bufp->fullBit(oldp+148,(vlSelfRef.multiply_block__DOT__m8__DOT__fa29__DOT__a));
    bufp->fullBit(oldp+149,(vlSelfRef.multiply_block__DOT__m8__DOT__fa29__DOT__b));
    bufp->fullBit(oldp+150,(vlSelfRef.multiply_block__DOT__m8__DOT__fa29__DOT__cin));
    bufp->fullBit(oldp+151,(vlSelfRef.multiply_block__DOT__m8__DOT__fa29__DOT__s));
    bufp->fullBit(oldp+152,(vlSelfRef.multiply_block__DOT__m8__DOT__fa29__DOT__cout));
    bufp->fullBit(oldp+153,(vlSelfRef.multiply_block__DOT__m8__DOT__fa30__DOT__a));
    bufp->fullBit(oldp+154,(vlSelfRef.multiply_block__DOT__m8__DOT__fa30__DOT__b));
    bufp->fullBit(oldp+155,(vlSelfRef.multiply_block__DOT__m8__DOT__fa30__DOT__cin));
    bufp->fullBit(oldp+156,(vlSelfRef.multiply_block__DOT__m8__DOT__fa30__DOT__s));
    bufp->fullBit(oldp+157,(vlSelfRef.multiply_block__DOT__m8__DOT__fa30__DOT__cout));
    bufp->fullBit(oldp+158,(vlSelfRef.multiply_block__DOT__m8__DOT__fa31__DOT__a));
    bufp->fullBit(oldp+159,(vlSelfRef.multiply_block__DOT__m8__DOT__fa31__DOT__b));
    bufp->fullBit(oldp+160,(vlSelfRef.multiply_block__DOT__m8__DOT__fa31__DOT__cin));
    bufp->fullBit(oldp+161,(vlSelfRef.multiply_block__DOT__m8__DOT__fa31__DOT__s));
    bufp->fullBit(oldp+162,(vlSelfRef.multiply_block__DOT__m8__DOT__fa31__DOT__cout));
    bufp->fullBit(oldp+163,(vlSelfRef.multiply_block__DOT__m8__DOT__fa32__DOT__a));
    bufp->fullBit(oldp+164,(vlSelfRef.multiply_block__DOT__m8__DOT__fa32__DOT__b));
    bufp->fullBit(oldp+165,(vlSelfRef.multiply_block__DOT__m8__DOT__fa32__DOT__cin));
    bufp->fullBit(oldp+166,(vlSelfRef.multiply_block__DOT__m8__DOT__fa32__DOT__s));
    bufp->fullBit(oldp+167,(vlSelfRef.multiply_block__DOT__m8__DOT__fa32__DOT__cout));
    bufp->fullBit(oldp+168,(vlSelfRef.multiply_block__DOT__m8__DOT__fa33__DOT__a));
    bufp->fullBit(oldp+169,(vlSelfRef.multiply_block__DOT__m8__DOT__fa33__DOT__b));
    bufp->fullBit(oldp+170,(vlSelfRef.multiply_block__DOT__m8__DOT__fa33__DOT__cin));
    bufp->fullBit(oldp+171,(vlSelfRef.multiply_block__DOT__m8__DOT__fa33__DOT__s));
    bufp->fullBit(oldp+172,(vlSelfRef.multiply_block__DOT__m8__DOT__fa33__DOT__cout));
    bufp->fullBit(oldp+173,(vlSelfRef.multiply_block__DOT__m8__DOT__fa34__DOT__a));
    bufp->fullBit(oldp+174,(vlSelfRef.multiply_block__DOT__m8__DOT__fa34__DOT__b));
    bufp->fullBit(oldp+175,(vlSelfRef.multiply_block__DOT__m8__DOT__fa34__DOT__cin));
    bufp->fullBit(oldp+176,(vlSelfRef.multiply_block__DOT__m8__DOT__fa34__DOT__s));
    bufp->fullBit(oldp+177,(vlSelfRef.multiply_block__DOT__m8__DOT__fa34__DOT__cout));
    bufp->fullBit(oldp+178,(vlSelfRef.multiply_block__DOT__m8__DOT__fa35__DOT__a));
    bufp->fullBit(oldp+179,(vlSelfRef.multiply_block__DOT__m8__DOT__fa35__DOT__b));
    bufp->fullBit(oldp+180,(vlSelfRef.multiply_block__DOT__m8__DOT__fa35__DOT__cin));
    bufp->fullBit(oldp+181,(vlSelfRef.multiply_block__DOT__m8__DOT__fa35__DOT__s));
    bufp->fullBit(oldp+182,(vlSelfRef.multiply_block__DOT__m8__DOT__fa35__DOT__cout));
    bufp->fullBit(oldp+183,(vlSelfRef.multiply_block__DOT__m8__DOT__fa36__DOT__a));
    bufp->fullBit(oldp+184,(vlSelfRef.multiply_block__DOT__m8__DOT__fa36__DOT__b));
    bufp->fullBit(oldp+185,(vlSelfRef.multiply_block__DOT__m8__DOT__fa36__DOT__cin));
    bufp->fullBit(oldp+186,(vlSelfRef.multiply_block__DOT__m8__DOT__fa36__DOT__s));
    bufp->fullBit(oldp+187,(vlSelfRef.multiply_block__DOT__m8__DOT__fa36__DOT__cout));
    bufp->fullBit(oldp+188,(vlSelfRef.multiply_block__DOT__m8__DOT__fa37__DOT__a));
    bufp->fullBit(oldp+189,(vlSelfRef.multiply_block__DOT__m8__DOT__fa37__DOT__b));
    bufp->fullBit(oldp+190,(vlSelfRef.multiply_block__DOT__m8__DOT__fa37__DOT__cin));
    bufp->fullBit(oldp+191,(vlSelfRef.multiply_block__DOT__m8__DOT__fa37__DOT__s));
    bufp->fullBit(oldp+192,(vlSelfRef.multiply_block__DOT__m8__DOT__fa37__DOT__cout));
    bufp->fullBit(oldp+193,(vlSelfRef.multiply_block__DOT__m8__DOT__fa38__DOT__a));
    bufp->fullBit(oldp+194,(vlSelfRef.multiply_block__DOT__m8__DOT__fa38__DOT__b));
    bufp->fullBit(oldp+195,(vlSelfRef.multiply_block__DOT__m8__DOT__fa38__DOT__cin));
    bufp->fullBit(oldp+196,(vlSelfRef.multiply_block__DOT__m8__DOT__fa38__DOT__s));
    bufp->fullBit(oldp+197,(vlSelfRef.multiply_block__DOT__m8__DOT__fa38__DOT__cout));
    bufp->fullBit(oldp+198,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_1__DOT__a));
    bufp->fullBit(oldp+199,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_1__DOT__b));
    bufp->fullBit(oldp+200,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_1__DOT__cin));
    bufp->fullBit(oldp+201,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_1__DOT__s));
    bufp->fullBit(oldp+202,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_1__DOT__cout));
    bufp->fullBit(oldp+203,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_10__DOT__a));
    bufp->fullBit(oldp+204,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_10__DOT__b));
    bufp->fullBit(oldp+205,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_10__DOT__cin));
    bufp->fullBit(oldp+206,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_10__DOT__s));
    bufp->fullBit(oldp+207,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_10__DOT__cout));
    bufp->fullBit(oldp+208,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_11__DOT__a));
    bufp->fullBit(oldp+209,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_11__DOT__b));
    bufp->fullBit(oldp+210,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_11__DOT__cin));
    bufp->fullBit(oldp+211,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_11__DOT__s));
    bufp->fullBit(oldp+212,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_11__DOT__cout));
    bufp->fullBit(oldp+213,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_12__DOT__a));
    bufp->fullBit(oldp+214,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_12__DOT__b));
    bufp->fullBit(oldp+215,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_12__DOT__cin));
    bufp->fullBit(oldp+216,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_12__DOT__s));
    bufp->fullBit(oldp+217,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_12__DOT__cout));
    bufp->fullBit(oldp+218,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_2__DOT__a));
    bufp->fullBit(oldp+219,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_2__DOT__b));
    bufp->fullBit(oldp+220,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_2__DOT__cin));
    bufp->fullBit(oldp+221,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_2__DOT__s));
    bufp->fullBit(oldp+222,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_2__DOT__cout));
    bufp->fullBit(oldp+223,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_3__DOT__a));
    bufp->fullBit(oldp+224,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_3__DOT__b));
    bufp->fullBit(oldp+225,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_3__DOT__cin));
    bufp->fullBit(oldp+226,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_3__DOT__s));
    bufp->fullBit(oldp+227,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_3__DOT__cout));
    bufp->fullBit(oldp+228,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_4__DOT__a));
    bufp->fullBit(oldp+229,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_4__DOT__b));
    bufp->fullBit(oldp+230,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_4__DOT__cin));
    bufp->fullBit(oldp+231,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_4__DOT__s));
    bufp->fullBit(oldp+232,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_4__DOT__cout));
    bufp->fullBit(oldp+233,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_5__DOT__a));
    bufp->fullBit(oldp+234,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_5__DOT__b));
    bufp->fullBit(oldp+235,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_5__DOT__cin));
    bufp->fullBit(oldp+236,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_5__DOT__s));
    bufp->fullBit(oldp+237,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_5__DOT__cout));
    bufp->fullBit(oldp+238,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_6__DOT__a));
    bufp->fullBit(oldp+239,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_6__DOT__b));
    bufp->fullBit(oldp+240,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_6__DOT__cin));
    bufp->fullBit(oldp+241,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_6__DOT__s));
    bufp->fullBit(oldp+242,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_6__DOT__cout));
    bufp->fullBit(oldp+243,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_7__DOT__a));
    bufp->fullBit(oldp+244,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_7__DOT__b));
    bufp->fullBit(oldp+245,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_7__DOT__cin));
    bufp->fullBit(oldp+246,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_7__DOT__s));
    bufp->fullBit(oldp+247,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_7__DOT__cout));
    bufp->fullBit(oldp+248,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_8__DOT__a));
    bufp->fullBit(oldp+249,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_8__DOT__b));
    bufp->fullBit(oldp+250,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_8__DOT__cin));
    bufp->fullBit(oldp+251,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_8__DOT__s));
    bufp->fullBit(oldp+252,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_8__DOT__cout));
    bufp->fullBit(oldp+253,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_9__DOT__a));
    bufp->fullBit(oldp+254,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_9__DOT__b));
    bufp->fullBit(oldp+255,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_9__DOT__cin));
    bufp->fullBit(oldp+256,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_9__DOT__s));
    bufp->fullBit(oldp+257,(vlSelfRef.multiply_block__DOT__m8__DOT__fa_9__DOT__cout));
    bufp->fullBit(oldp+258,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_1__DOT__a));
    bufp->fullBit(oldp+259,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_1__DOT__b));
    bufp->fullBit(oldp+260,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_1__DOT__s));
    bufp->fullBit(oldp+261,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_1__DOT__cout));
    bufp->fullBit(oldp+262,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_10__DOT__a));
    bufp->fullBit(oldp+263,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_10__DOT__b));
    bufp->fullBit(oldp+264,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_10__DOT__s));
    bufp->fullBit(oldp+265,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_10__DOT__cout));
    bufp->fullBit(oldp+266,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_11__DOT__a));
    bufp->fullBit(oldp+267,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_11__DOT__b));
    bufp->fullBit(oldp+268,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_11__DOT__s));
    bufp->fullBit(oldp+269,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_11__DOT__cout));
    bufp->fullBit(oldp+270,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_12__DOT__a));
    bufp->fullBit(oldp+271,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_12__DOT__b));
    bufp->fullBit(oldp+272,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_12__DOT__s));
    bufp->fullBit(oldp+273,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_12__DOT__cout));
    bufp->fullBit(oldp+274,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_13__DOT__a));
    bufp->fullBit(oldp+275,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_13__DOT__b));
    bufp->fullBit(oldp+276,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_13__DOT__s));
    bufp->fullBit(oldp+277,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_13__DOT__cout));
    bufp->fullBit(oldp+278,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_14__DOT__a));
    bufp->fullBit(oldp+279,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_14__DOT__b));
    bufp->fullBit(oldp+280,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_14__DOT__s));
    bufp->fullBit(oldp+281,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_14__DOT__cout));
    bufp->fullBit(oldp+282,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_15__DOT__a));
    bufp->fullBit(oldp+283,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_15__DOT__b));
    bufp->fullBit(oldp+284,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_15__DOT__s));
    bufp->fullBit(oldp+285,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_15__DOT__cout));
    bufp->fullBit(oldp+286,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_2__DOT__a));
    bufp->fullBit(oldp+287,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_2__DOT__b));
    bufp->fullBit(oldp+288,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_2__DOT__s));
    bufp->fullBit(oldp+289,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_2__DOT__cout));
    bufp->fullBit(oldp+290,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_3__DOT__a));
    bufp->fullBit(oldp+291,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_3__DOT__b));
    bufp->fullBit(oldp+292,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_3__DOT__s));
    bufp->fullBit(oldp+293,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_3__DOT__cout));
    bufp->fullBit(oldp+294,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_4__DOT__a));
    bufp->fullBit(oldp+295,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_4__DOT__b));
    bufp->fullBit(oldp+296,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_4__DOT__s));
    bufp->fullBit(oldp+297,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_4__DOT__cout));
    bufp->fullBit(oldp+298,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_5__DOT__a));
    bufp->fullBit(oldp+299,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_5__DOT__b));
    bufp->fullBit(oldp+300,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_5__DOT__s));
    bufp->fullBit(oldp+301,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_5__DOT__cout));
    bufp->fullBit(oldp+302,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_6__DOT__a));
    bufp->fullBit(oldp+303,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_6__DOT__b));
    bufp->fullBit(oldp+304,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_6__DOT__s));
    bufp->fullBit(oldp+305,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_6__DOT__cout));
    bufp->fullBit(oldp+306,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_7__DOT__a));
    bufp->fullBit(oldp+307,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_7__DOT__b));
    bufp->fullBit(oldp+308,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_7__DOT__s));
    bufp->fullBit(oldp+309,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_7__DOT__cout));
    bufp->fullBit(oldp+310,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_8__DOT__a));
    bufp->fullBit(oldp+311,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_8__DOT__b));
    bufp->fullBit(oldp+312,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_8__DOT__s));
    bufp->fullBit(oldp+313,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_8__DOT__cout));
    bufp->fullBit(oldp+314,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_9__DOT__a));
    bufp->fullBit(oldp+315,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_9__DOT__b));
    bufp->fullBit(oldp+316,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_9__DOT__s));
    bufp->fullBit(oldp+317,(vlSelfRef.multiply_block__DOT__m8__DOT__ha_9__DOT__cout));
    bufp->fullIData(oldp+318,(vlSelfRef.multiply_block__DOT__m8__DOT__unnamedblk1__DOT__i),32);
    bufp->fullIData(oldp+319,(vlSelfRef.multiply_block__DOT__m8__DOT__unnamedblk1__DOT__unnamedblk2__DOT__j),32);
    bufp->fullCData(oldp+320,(vlSelfRef.multiply_block__DOT__s2u_inst__DOT__in),8);
    bufp->fullCData(oldp+321,(vlSelfRef.multiply_block__DOT__s2u_inst__DOT__out),8);
    bufp->fullBit(oldp+322,(vlSelfRef.multiply_block__DOT__s2u_inst__DOT__is_neg));
    bufp->fullSData(oldp+323,(vlSelfRef.multiply_block__DOT__u2s_inst__DOT__in),16);
    bufp->fullBit(oldp+324,(vlSelfRef.multiply_block__DOT__u2s_inst__DOT__is_neg));
    bufp->fullSData(oldp+325,(vlSelfRef.multiply_block__DOT__u2s_inst__DOT__out),16);
}
